# Setup
title:               AkiVaMu
tagline:             Just tiny things come to mind...
baseurl:             ''
paginate:            5
permalink:           :slug

# About
author:
  name:              akivamu
  url:               https://akivamu.github.io
  email:             akivamu@gmail.com

exclude: ['Gemfile.lock', 'Gemfile']

gems:
  - jekyll-paginate

sass:
  style: compressed
  sass_dir: _sass