# Setup
title:               AkiVaMu
tagline:             Just tiny things come to mind...
baseurl:             ''
paginate:            1
permalink:           :slug

# About
author:
  name:              akivamu
  url:               https://akivamu.github.io
  email:             akivamu@gmail.com

exclude: ['Gemfile.lock', 'Gemfile']

gems: [jekyll-paginate]
