# Setup
title:               AkiVaMu
tagline:             Just tiny things come to mind...
baseurl:             ''
paginate:            5
permalink:           :slug

# About
repository:          akivamu/akivamu.github.io
author:
  name:              akivamu
  url:               https://akivamu.github.io
  email:             akivamu@gmail.com

exclude: ['Gemfile.lock', 'Gemfile']

sass:
  style: compressed
  sass_dir: _sass